name: mmHub
author: Flipwhatthezip2
version: 1.0
main: mcm.Flipwhatthezip2.mmHub.Core
commands:
  hub:
    description: Sends player to a hub server.
  mod:
    description: All moderator commands.
  betamode:
    description: Toggles beta mode.